'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
    the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
'''

F_sequence = [1, 2]
even_F_sequence = []
product = 0

while F_sequence[-1] < 4000000:
    F_sequence.append(F_sequence[-1] + F_sequence[-2])

for item in F_sequence:
    if (item % 2) == 0:
        even_F_sequence.append(item)

#print(even_F_sequence)
print(sum(even_F_sequence))
