'''Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj|
is minimised; what is the value of D?'''

pentagonal_list = {}
counter = 1
while len(pentagonal_list) < 3000:
    pentagonal_list[(int(counter * (counter * 3 - 1)/2))] = None
    counter += 1

counter = 0
for n1 in pentagonal_list:
    if counter % 1000 == 0:
        print(counter)
    for n2 in pentagonal_list:
        if (n1 + n2) in pentagonal_list:
            if (n1 - n2) in pentagonal_list:
                print('yes', n1, n2, n1 - n2)
    counter += 1
