'''The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?'''


import sys


def factor_length(number):
    factors_set = set()
    bottom = 1
    top = number

    while bottom < top:
        if (number % bottom) == 0:
            top = int(number / bottom)
            factors_set.add(bottom)
            factors_set.add(top)
        bottom += 1

    if len(factors_set) > 500:
        print(number, sorted(factors_set))
        sys.exit(0)

last_number = 0
count = 1
while True:
    last_number += count
    if (count % 1000) == 0:
        print(count, last_number)
    factor_length(last_number)
    count += 1
