'''Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.'''


counter = 1
t_dict = {}
p_dict = {}
h_dict = {}
while counter < 1000000:
    t_dict[int(counter * (counter + 1)/2)] = counter
    p_dict[int(counter * ((3 * counter) - 1) / 2)] = counter
    h_dict[int(counter * ((2 * counter) - 1))] = counter
    counter += 1

for item in t_dict:
    if item in p_dict and item in h_dict:
        print('Winner', item)
